name = "bond-tracker"
main = "src/index.js"
compatibility_date = "2025-07-13"

[[d1_databases]]
binding = "DB"
database_name = "bond_coin_db"
database_id = "otomatik oluşturulacak"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.