name = "bond-tracker"
main = "src/index.js"
compatibility_date = "2025-07-13"

[[d1_databases]]
binding = "DB"
database_name = "bond-tracker"
database_id = "497ae0af-457f-4fa0-9151-ca876db2cf8f"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.